// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sulfjucbphhjmdghpoxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1bGZqdWNicGhoam1kZ2hwb3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDcwNjcsImV4cCI6MjA1ODk4MzA2N30.kpT_i4Vs5KJvrxAiUCybyocJJu3aSKJIYpu8uq8IH78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);